FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN adduser --quiet --disabled-password qtuser && usermod -a -G audio qtuser
ENV LIBGL_ALWAYS_INDIRECT=1

RUN apt-get update -y
RUN apt-get install -y python3-pip python3.9 build-essential libgl1-mesa-glx ffmpeg libsm6 libxext6  \
    libegl1 libxcb-xinerama0 '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev  \
    libxkbcommon-dev libxkbcommon-x11-dev

#EXPOSE 5000
#ENV FLASK_APP 'app.py'
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

#ENTRYPOINT [ "flask"]
#CMD [ "r_u_n", "--host", "0.0.0.0"]
